# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 492ddba766623bd6b96856ba41d2eb2a29465afb617303b138f230bd2894ba127514a07461e8956725b6ba0889e8b85249737b56deb251eae420088c33a05b9b

test:
  secret_key_base: 9544a6107fed8d8db9130a93e3ac61c589d34fbab573e1a5068cd4d2e369546cfffce3e18489e4e3a4222f0219c5160e1a4c619c3e1266a6343f54441cd0ead3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
